name: Run R Scripts From CAHOOT.zip

on: [push]

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install required R packages
      run: |
        Rscript -e 'install.packages(c(
          "ggplot2", "dplyr", "reshape2", 
          "MASS", "reshape", "lubridate", 
          "rddtools", "data.table"
        ), dependencies = TRUE)'

    - name: Unzip R scripts
      run: |
        unzip CAHOOT.zip -d extracted_scripts
        ls extracted_scripts

    - name: Run all R scripts in the ZIP
      run: |
        for script in extracted_scripts/*.R; do
          echo "Running $script"
          Rscript "$script"
        done
